# Generated by Django 5.0.1 on 2024-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='categories',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sub_categories',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
