# Generated by Django 5.0.1 on 2024-04-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_productdetails_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='sub_categories',
        ),
    ]
