# Generated by Django 5.0.1 on 2024-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_productdetails_sub_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='categories',
            new_name='product_category',
        ),
    ]
