# Generated by Django 5.0.1 on 2024-04-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_categories_productdetails_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='sub_categories',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
