# Generated by Django 5.0.1 on 2024-04-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_productdetails_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=40)),
                ('product_details_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productdetails')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
