# Generated by Django 5.0.1 on 2024-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_deliverydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='city',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='instruction',
            field=models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='product_status',
            field=models.CharField(default='Order Placed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
