# Generated by Django 5.0.1 on 2024-05-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_deliverydetails_city_deliverydetails_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='phone',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
