# Generated by Django 5.0.1 on 2024-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_deliverydetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='fullname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
