# Generated by Django 5.0.1 on 2024-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_deliverydetails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
