# Generated by Django 5.0.1 on 2024-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_deliverydetails_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
