# Generated by Django 5.0.1 on 2024-05-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_deliverydetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
