# Generated by Django 5.0.1 on 2024-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_deliverydetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_stock',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
