# Generated by Django 5.0.1 on 2024-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_deliverydetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_1', models.CharField(max_length=10, null=True)),
                ('sub_category_2', models.CharField(max_length=10, null=True)),
                ('sub_category_3', models.CharField(max_length=10, null=True)),
                ('sub_category_4', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
