# Generated by Django 5.0.1 on 2024-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_delete_category_productdetails_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_stock',
            field=models.IntegerField(null=True),
        ),
    ]
