# Generated by Django 5.0.1 on 2024-05-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_productdetails_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_quantity',
        ),
    ]
