# Generated by Django 5.0.1 on 2024-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_productdetails_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(max_length=20, null='PAID'),
        ),
    ]
